### ISSUE TITLE
Received channel answer event with no call direction: "<No Body>"

### ISSUE THREAD

**Issue by JonHVU** [friends-of-freeswitch/mod_prometheus#8] opened 2017-01-12 11:36 UTC
Hi Moises,

Great module, really like it!
I could see from a previous issue there was a segfault, and I dont get that, however I do keep seeing;

2017-01-12 11:29:08.272726 [WARNING] mod_prometheus.rs:196 Received channel answer event with no call direction: "<No Body>"
2017-01-12 11:33:48.452755 [WARNING] mod_prometheus.rs:220 Received channel hangup event with no call answer time information: "<No Body>"

This is when I am using git clone https://github.com/moises-silva/mod_prometheus, with version 1.6.12.

I have tried adding direction in dialplan, but just want to make sure I have the latest version, and if there is any other issue?

Thanks and sorry for the noise!

Jon

**Comment by moises-silva** [comment] 2017-01-14 00:13
Hello @JonHVU 

That is odd. It appears there's situations when FreeSWITCH creates channels without direction, or when the channel variable is not yet populated. How are you generating those calls? do all calls lack the call direction?

**Comment by JonHVU** [comment] 2017-01-14 14:27
Hello,

Thanks for the reply, hope you are well?

I have added info application to my dialplan and I do see in events;

Call-Direction: [inbound]
Presence-Call-Direction: [inbound]

However I still see the warning message.

2017-01-14 14:18:59.932733 [WARNING] mod_prometheus.rs:178 Received channel create event with no call direction: "<No Body>"

This is on a kamailio/FreeSWITCH environment, where I currently test from a soft-client, which is registered with kamailio, kamailio then proxies the request to FreeSWITCH at the moment to a simple dialplan which does transcoding as required, and just bridges call back out again.

This is on FreeSWITCH Version 1.6.12+git~20161118T153754Z~f18f82cffe~64bit

If you want me to get some logs/debug let me know and will gladly provide, unless I am missing something? 

Also I have tried to add variables in the dialplans for call-direction but that doesnt seem to help.

Any tips appreciated!

Thanks

Jon

**Comment by moises-silva** [comment] 2017-01-16 11:36
@JonHVU Yeah I'd like to see a debug log from FreeSWITCH. Note I mostly have tested this against master, and because of the conversion from C to Rust, may be some of the C structures were different in 1.6. I'll try to test with 1.6 this weekend.

**Comment by JonHVU** [comment] 2017-05-08 12:09
Hi Moises, hope you are well? I have just picked this back up again, and I can still see this in my console screen;

2017-05-08 12:05:44.302674 [WARNING] mod_prometheus.rs:178 Received channel create event with no call direction: "<No Body>"

And I can see its not recording failed calls correctly, I presume as a result? 

This is in version FreeSWITCH Version 1.6.12+git~20161118T153754Z~f18f82cffe~64bit.

Did you manage to recreate or do I need to collect debug?

Thanks!

**Comment by JonHVU** [comment] 2017-05-12 11:59
Hi there,

Are you still active with this module as we would really like to implement as it looks great, I just need to get to the bottom of the call direction issue, as it doesnt appear to record all stats.

Any help would be appreciated.

Jon

**Comment by moises-silva** [comment] 2017-05-15 03:14
Sorry @JonHVU, it's been busy lately for me and this project hasn't really been a priority for me. I fully intent to give it a try on 1.6 tomorrow. In the meantime, can you tell me how often does it happen? can you reproduce the problem at will? any information you can provide for me to reproduce the problem tomorrow will help me fix it quickly.

Thanks

**Comment by JonHVU** [comment] 2017-05-15 09:56
[PromethusFSdebug.txt](https://github.com/moises-silva/mod_prometheus/files/1000724/PromethusFSdebug.txt)
Hi @moises-silva  thanks for the response, I appreciate it! Please see logs attached for an outbound call to my mobile via Freeswitch, I set loglevel to 7 and enabled sofia debug as well.
When then running the stats, I dont see any changes in outbound stats, I only see overall stats being modified so I presume I need to determine direction somewhere?
both inbound and outbound will pass through FS for transcoding etc.

If you want me to enable anything else in terms of debug let me know.

Thanks
[StatsSeen.txt](https://github.com/moises-silva/mod_prometheus/files/1000718/StatsSeen.txt)

**Comment by moises-silva** [comment] 2017-05-16 05:34
@JonHVU I was able to reproduce the issue. I am very surprised I didn't notice this before. This should be fixed now by https://github.com/moises-silva/freeswitchrs/commit/c78983e644bef5058a62fbc72a80b1b67d323afc

You need to rebuild the module to pick up the latest freeswitchrs library.

Please confirm when you test and I'll close this issue.

Thanks!

**Comment by JonHVU** [comment] 2017-05-16 11:52
Hi @moises-silva thats awesome thank you so much for fixing.

In terms of the call direction, where does your module take that information from? Is it taken from the channel events generated, and I pass calls in and out of freeswitch, so do I need to set this in dialplan so it records accurately? 

Thanks

Jon

**Comment by moises-silva** [comment] 2017-05-16 14:02
Hey @JonHVU the direction is something that FreeSWITCH sets on its own, you don't need to set it, it's part of the caller profile in the 'Call-Direction' session event field.

**Comment by JonHVU** [comment] 2017-05-16 14:20
Hey @moises-silva  ok cool thanks again for the help, looking good now!

**Closed as completed** 2017-05-16 14:30 UTC
